export { Header } from './Header';
export { ProductGrid } from './ProductsGrid';
export { Footer } from './Footer';
export { HeadingPage } from './HeadingPage';
export { FilterMenu } from './FilterMenu';
export { Loader } from './Loader';
export { OnlinePay } from './OnlinePay';
export { Consultation } from './Consultation';
export { FollowInst } from './FollowInst';
